export const MOVE_SHAPE = "MOVE_SHAPE";

export const GET_DB_DATA_SUCCESS = "GET_DB_DATA_SUCCESS";
export const GET_DB_DATA_FETCHING = "GET_DB_DATA_FETCHING";
export const GET_DB_DATA_ERROR = "GET_DB_DATA_ERROR";

export const SET_DB_DATA_SUCCESS = "SET_DB_DATA_SUCCESS";
export const SET_DB_DATA_ERROR = "SET_DB_DATA_ERROR";

export const STATISTICS_DATA = "STATISTICS_DATA";
