import { HERBIVOROUS, PREDATOR } from "./animalType";

export default {
    width: 10,
    height: 10,

    locations: [
        {
            id: "31b57440-28f6-44ba-8878-f96183fffff7",
            x: 2,
            y: 2,
            color: "green",
            resource: "grass",
        },
        {
            id: "0fcec4ce-55ae-4ecc-94fc-6c215eb3dcd2",
            x: 3,
            y: 3,
            color: "green",
            resource: "grass",
        },
        {
            id: "7e762ff9-db0c-4948-9a62-384ebe4a683d",
            x: 4,
            y: 3,
            color: "green",
            resource: "grass",
        },
        {
            id: "bcb0d5ef-edef-4d92-ae8b-919b65ee7f53",
            x: 8,
            y: 8,
            color: "green",
            resource: "grass",
        },
        {
            id: "1ccc5038-8eb0-4f8f-8608-e8eba0cdd789",
            x: 7,
            y: 8,
            color: "green",
            resource: "grass",
        },
        {
            id: "1f667d29-2720-477c-a041-edecbe899a7b",
            x: 7,
            y: 7,
            color: "green",
            resource: "grass",
        },
        {
            id: "73b1a425-61e9-4099-b66c-b66fe8e90702",
            x: 8,
            y: 7,
            color: "green",
            resource: "grass",
        },
        {
            id: "12ffe1e6-4585-4506-8a6d-026c82b3f12a",
            x: 4,
            y: 2,
            color: "#6ec6e4",
            resource: "water",
        },
    ],

    npc: [
        {
            id: "226c48d3-0e55-4e73-8198-4470e049f60d",
            x: 3,
            y: 5,
            helth: 100,
            food: 100,
            color: "gray",
            typeName: "Rabbit",
            type: HERBIVOROUS,
            resource: "meat",
            foodType: "grass",
        },
        {
            id: "502c9a96-75db-45f1-a9eb-163ddea71c0d",
            x: 4,
            y: 5,
            helth: 100,
            food: 100,
            color: "gray",
            typeName: "Rabbit",
            type: HERBIVOROUS,
            resource: "meat",
            foodType: "grass",
        },
        {
            id: "c11c037e-ce99-4d52-95d0-0532bec14405",
            x: 5,
            y: 5,
            helth: 100,
            food: 100,
            color: "gray",
            typeName: "Rabbit",
            type: HERBIVOROUS,
            resource: "meat",
            foodType: "grass",
        },
        {
            id: "febb2f6f-2fab-471e-9cd8-29e1e3717c7b",
            x: 6,
            y: 5,
            helth: 100,
            food: 100,
            color: "gray",
            typeName: "Rabbit",
            type: HERBIVOROUS,
            resource: "meat",
            foodType: "grass",
        },
        {
            id: "435fa23c-9235-40dd-9907-98403d10e920",
            x: 3,
            y: 6,
            helth: 100,
            food: 100,
            color: "gray",
            typeName: "Rabbit",
            type: HERBIVOROUS,
            resource: "meat",
            foodType: "grass",
        },
        {
            id: "7ccfc6e5-f5e1-4271-93d0-af0bca424100",
            x: 4,
            y: 6,
            helth: 100,
            food: 100,
            color: "gray",
            typeName: "Rabbit",
            type: HERBIVOROUS,
            resource: "meat",
            foodType: "grass",
        },
        {
            id: "f53df5d9-8107-4557-afea-451d41721608",
            x: 5,
            y: 6,
            helth: 100,
            food: 100,
            color: "gray",
            typeName: "Rabbit",
            type: HERBIVOROUS,
            resource: "meat",
            foodType: "grass",
        },
        {
            id: "fdcd36ab-2a6d-4dbc-a459-007b9396ae76",
            x: 4,
            y: 6,
            helth: 100,
            food: 100,
            color: "gray",
            typeName: "Rabbit",
            type: HERBIVOROUS,
            resource: "meat",
            foodType: "grass",
        },
        {
            id: "847aa37b-8548-4654-a812-a7da5766a236",
            x: 5,
            y: 6,
            helth: 100,
            food: 100,
            color: "gray",
            typeName: "Rabbit",
            type: HERBIVOROUS,
            resource: "meat",
            foodType: "grass",
        },
        {
            id: "3ce572e3-e6be-47f2-a05f-e023be64f255",
            x: 5,
            y: 5,
            helth: 100,
            food: 100,
            color: "black",
            type: PREDATOR,
            typeName: "Wolf",
            resource: "meat",
            foodType: "meat",
        },
        {
            id: "d067bbcb-eda2-42e8-86c0-18e540971cb6",
            x: 5,
            y: 5,
            helth: 100,
            food: 100,
            color: "red",
            type: PREDATOR,
            typeName: "Wolf",
            resource: "meat",
            foodType: "meat",
        },
        {
            id: "0643b879-d851-4495-9a80-92b0ee9a4d76",
            x: 5,
            y: 5,
            helth: 100,
            food: 100,
            color: "gray",
            type: PREDATOR,
            typeName: "Wolf",
            resource: "meat",
            foodType: "meat",
        },
        {
            id: "51576dba-4d81-4bd5-a42d-37344c750687",
            x: 8,
            y: 3,
            helth: 100,
            food: 100,
            color: "black",
            type: PREDATOR,
            typeName: "Lion",
            resource: "meat",
            foodType: "meat",
        },
        {
            id: "f882e0e9-118e-4ade-8a86-7e671a2bcd64",
            x: 7,
            y: 1,
            helth: 100,
            food: 100,
            color: "blue",
            type: PREDATOR,
            typeName: "Lion",
            resource: "meat",
            foodType: "meat",
        },
    ],
};
